name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      cachekey: Testing 

    steps:
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ env.cachekey }}
        restore-keys: ${{ env.cachekey }}

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        cache: true


