name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      cachekey: Testing 

    steps:

    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ env.cachekey }}
        restore-keys: ${{ env.cachekey }}

    - uses: actions/setup-dotnet@v2
    - name: Setting DotNet
      with:
        dotnet-version: 6.0.x     

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
    
